// Project Euler: Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

#include <iostream>

using namespace std;

int main()
{
	int sum = 0;
	int n = 4e6;

	int a1 = 1;
	int a2 = 1;
	for (;;)
	{
		int an = a1 + a2;
		if (an > n)
			break;
		if (an % 2 == 0)
			sum += an;
		a1 = a2;
		a2 = an;
	}

	cout << sum << endl;
	return 0;
}
